### ISSUE TITLE
MAX_VERIFICATION_METHOD_NUMBER definition is misleading?

### ISSUE THREAD

**Issue by patlo-iog** [input-output-hk/prism-did-method-spec#39]
The [MAX_VERIFICATION_METHOD_NUMBER definition](https://github.com/input-output-hk/prism-did-method-spec/blob/main/w3c-spec/PRISM-method.md?plain=1#L36) states

>  Maximum number of active verification methods a DID Document can have at the same time.

The expectation is that the keys that *appear* in the DID document can't exceed `MAX_VERIFICATION_METHOD_NUMBER`.
But in [translation of DID document](https://github.com/input-output-hk/prism-did-method-spec/blob/main/w3c-spec/PRISM-method.md?plain=1#L781), keys with the usage of `MASTER_KEY` and `REVOCATION_KEY` are not included. So if the `MAX_VERIFICATION_METHOD_NUMBER` is 50, the number of max keys that appear in the DID document is 49? (`MASTER_KEY` is not shown)

>  Maximum number of active keys a DID can have at the same time

Should it be rephrased to ^^^ or something similar?

**Comment by EzequielPostan** [comment]
I think we can indeed re-phrase. Maybe stating the constant as the maximum number of active keys that are not `MASTER_KEY` nor `REVOCATION_KEY` 
It would be good in the same lines to get feedback on the numbers selected for the limits in general. But I can update this in the next PR with other minor corrections 

My apologies for the delay on replying here, and thank you @patlo-iog for the comment
