### ISSUE TITLE
[Feature Request] Threshold multi-sig controller

### ISSUE THREAD

**Issue by iFergal** [input-output-hk/prism-did-method-spec#42]
As an extension of #41, m-of-n multi-sig would be useful for control over a DID.

This also is referring to control over a DID document (so perhaps `controller` array and some `threshold` to meet).

Use-case examples:
- Board of a company where the DID represents the company.
- Building on #41, 2 parents controlling a child's DID.

Weighted votes would be even better - though this can become more cumbersome to express in a DID document (if it needs to).

**Comment by EzequielPostan** [comment]
this are interesting features, as you point out, the more complex the logic, the harder the implementation.
Depending on use case, and the precise level of expressiveness needed, there would be different ways to implement it. It will be good to get more use cases and refine their needs

**Comment by iFergal** [comment]
Yeah, I feel like something like this could have endless use cases, particularly in a business or legal context, or something in the IoT space. I'll try to think up some concrete ones.

As mentioned in https://github.com/input-output-hk/prism-did-method-spec/issues/41#issuecomment-1472014180 we can at least achieve n-of-n multi-sig with an array for `did.controller`.

One possible solution to make this (non-weighted) **threshold** multi-sig is a new top level property such as `did.controllerThreshold` (with some enforcement that the integer makes sense, given the length of `did.controller`).

The more refined **weighted threshold** multi-sig is as I said, more cumbersome to express, at least at the top-level of the DID document. Something I need to think about - maybe that is adding too much complexity.

**Comment by EzequielPostan** [comment]
apologies here too for the delay

I think I should refer to the [comment](https://github.com/input-output-hk/prism-did-method-spec/issues/41#issuecomment-1552301524) I left in #41 too

I think we should clarify that issue before this one.
Let me know @iFergal if I could close this issue or if I should keep it open. If inactive, I would prefer to keep it closed and reopen it once we have more input to add/discuss

Thank you again for the comments!

**Comment by EzequielPostan** [comment]
I am closing the issue to keep a clean view of active ones
Feel free to re-open if needed
