### ISSUE TITLE
Historical DID support is unclear

### ISSUE THREAD

**Issue by iFergal** [input-output-hk/prism-did-method-spec#43]
https://github.com/input-output-hk/prism-did-method-spec/blob/b3f38aeb77cecac86c2865eb2c22934ae27e1181/w3c-spec/PRISM-method.md?plain=1#L170 
I did not see this specifically in the “Read DID” section (or others).

If it supports this the API should be made more clear how this is supported (e.g. is it `versionTime` from the `did:core` spec)

If it's not supported then this is a feature request! It would be a great to add because otherwise a key rotation of an issuer essentially revokes any issued credentials as the key material is no longer available to the verifier. (See discussions here https://github.com/decentralized-identity/keri/issues/52 and https://github.com/w3c/did-core/issues/386)

**Comment by EzequielPostan** [comment]
I would say that you have discovered an edition error. The current version of the spec is not describing how to manage historical queries. I will have to correct this.

With respect to adding historical queries as a feature, it is something to evaluate.
Some other changes likely need to be described first. For example, the changes to `@context` should be stored (today the spec described to store just the last `@context`)
Thank you for spotting the error

**Comment by iFergal** [comment]
OK got it, thanks! Yep in that case, a feature request. :P

I think this will become more important as the space matures because actual real-world issuers will want to rotate keys for security reasons at some point and "refreshing" each issued VC to a new one with the new key may not be viable at all.

**Comment by EzequielPostan** [comment]
I will close this one to keep better visibility of active issues
We can re-open it if we see the need
