### ISSUE TITLE
[Feature Request] Looser verificationKey material restrictions

### ISSUE THREAD

**Issue by iFergal** [input-output-hk/prism-did-method-spec#45]
It makes sense to restrict the controller keys (`MASTER_KEY` and maybe `REVOCATION_KEY`) to simplify signature checks for DID document updates on the Atala nodes.

But restricting all `verificationMethod`s might reduce interoperability. For example, DIDComm key exchange using `keyAgreement` type `P-256` may be required for some interaction instead of `X25519`, or maybe some FIPS compliance.

`Multibase` encoding would also be nice instead of just JWK, and probably easy to support.

**Comment by EzequielPostan** [comment]
thank you for the comment :)
It is in the plans, as mentioned in the spec

> In future versions, more verification method types and keys will be supported.

we started with a smaller subset and a particular encoding, but it can be extended

**Comment by BS-IO** [comment]
I think it's a thin line to thread, balancing flexibility of implementation vs expected interoperability based on the spec. You could end up in a situation where the same did-method might not have interoperable verificationMethods.

Now that might be good for flexibility and increasing the usefulness of the implementation, but it could come at the cost interop. Imho, some constraints could be enabling as they set clear expectations and could help drive adoption.

**Comment by rodolfomiranda** [comment]
Adding more Crypto Suit types should be trivial and can be extended easily if needed, but need to define each in the spec.  Note that `JsonWebKey2020`  allows all JOSE crypto primitives in just one Suite, including `P-256` , see [here](https://w3c.github.io/vc-jws-2020/), so it seems that only a reference in the spec is needed.

**Comment by BS-IO** [comment]
@iFergal there's definitely power in defaults. I like the example of FIPS/NIST compliance you raise as we are taking those types of things into consideration. Maybe we could explore 'recommended defaults for categories of use-cases'?

**Comment by rodolfomiranda** [comment]
Fergal, that's a good option at least to easily extend to the curves defied in [jose-conformance](https://w3c.github.io/vc-jws-2020/#jose-conformance) section of `JsonWebKey2020`. @EzequielPostan what do you think?

**Comment by iFergal** [comment]
Indeed, the jose-conformance would likely cover a lot of use cases!

@BS-IO Sounds look a good idea! It's difficult to predict every use case, but FIPS/NIST compliance (for "mission-critical" use cases) and wherever the DID space is going in general is a good starting point. (I just happened to have the FIPS IoT one on hand from recent research :))

**Comment by EzequielPostan** [comment]
> Fergal, that's a good option at least to easily extend to the curves defied in [jose-conformance](https://w3c.github.io/vc-jws-2020/#jose-conformance) section of JsonWebKey2020. @EzequielPostan what do you think?

_apologies for the delay_
Yes, a priori, the support is not hard to add. Note that most EC types of keys can be added fairly easily by defining the encoding in our protobuf models (either the compressed or uncompressed versions)

With respect to adding even more general types of verification methods, there are trade offs on implementation. For example, the more generic the model, the harder to compress it in a compact way, which is a topic to consider given that we are storing events on-chain
In any case, as use cases reveal the need for more types we can examine how to add them; I like the suggestion from @BS-IO to have a list so we can make use cases and required keys more visible

**Comment by iFergal** [comment]
@EzequielPostan On that note, have there been any considerations given to not compress the key material directly but rather compress the entire metadata as a whole?

Overall EC should be a good place to start with. I'm sure plenty (often legacy) systems use RSA but right now not sure on the use cases that wouldn't allow them to migrate to EC.

**Comment by EzequielPostan** [comment]
I will close the issue to keep a cleaner view of active ones
We can re-open if needed
