### ISSUE TITLE
Incorrect full protobuf model for `DIDCreationData`

### ISSUE THREAD

**Issue by patlo-iog** [input-output-hk/prism-did-method-spec#48]
[The full protobuf definition](https://github.com/input-output-hk/prism-did-method-spec/blame/main/w3c-spec/PRISM-method.md#L1044) is missing `context` on `DIDCreationData` message. It should be the same as [create operation construction](https://github.com/input-output-hk/prism-did-method-spec/blame/main/w3c-spec/PRISM-method.md#L268).

**Comment by EzequielPostan** [comment]
Fixed in #49
