### ISSUE TITLE
Spec Example not compliant to DID Core spec

### ISSUE THREAD

**Issue by bsandmann** [input-output-hk/prism-did-method-spec#54]
Minor issue in the [example](https://github.com/input-output-hk/prism-did-method-spec/blob/main/w3c-spec/PRISM-method.md#example-did-document-json-ld):

The correct name for the Authentication-Method is just `authentication` and not `authenticationMethod`. See [here](https://www.w3.org/TR/did-core/#authentication)

**Comment by EzequielPostan** [comment]
hello, nice to e-meet you! And thank you for opening the issue :) 

This is indeed an error in the example. After a review, I see that the rest of the spec simply refers to the corresponding W3C names, so it seems to just be an error in that example. I will correct the text in a PR
